name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      tag_name: ${{ steps.get_tag.outputs.tag }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get tag name
      id: get_tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_tag.outputs.tag }}
        release_name: Edison Note ${{ steps.get_tag.outputs.tag }}
        body: |
          ## Changes in ${{ steps.get_tag.outputs.tag }}
          
          ### ✨ New Features
          - Feature updates and improvements
          
          ### 🐛 Bug Fixes
          - Various bug fixes and stability improvements
          
          ### 🔧 Technical Changes
          - Performance optimizations
          - Code quality improvements
          
          ## Installation
          
          Download the appropriate binary for your platform:
          - **Windows**: `edison-note-windows.exe`
          - **macOS**: `edison-note-macos.dmg` 
          - **Linux**: `edison-note-linux.AppImage`
          
          For installation from source, see our [README](https://github.com/prequired/enote/blob/main/README.md).
        draft: false
        prerelease: false

  build:
    name: Build and Upload
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: edison-note
            asset_name: edison-note-linux
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: edison-note.exe
            asset_name: edison-note-windows.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: edison-note
            asset_name: edison-note-macos

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.0-dev libgtk-3-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build release binary
      run: cargo build --release --target ${{ matrix.target }}

    - name: Strip binary (Unix)
      if: matrix.os != 'windows-latest'
      run: strip target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        asset_content_type: application/octet-stream